---
title: "R Notebook"
output:
  html_notebook: default
  html_document: default
---
```{r,cache=T}
source('../Simulations/LinearModel/Coefficients.R')
source('../Simulations/LinearModel/Covariates.R')
source('../Simulations/LinearModel/noise.R')
source('../Simulations/LinearModel/LinearModel.R')
library(rstan)
N=1000
M=20
Q=1
P=1
K=4
set.seed(123)
X <- covariateMatrix(N = N, M=M,covariatesVar = rep(1,M))
Z <- covariateMatrix(N=N,M = P)
E <- iidNormal(N=N,traits = Q,sdI = 0.0016)
B <- replicate(
  n=Q, mixtureCoefSingle(
    M = M,proportions = rep(1/K,K),variance = c(0.0016,1e-4,0.04,0.01)
    )
  )[1,]
B <- t(do.call(what = rbind,args = B))
components <- c(0.0016,1e-4,0.04,0.01)
U <- unlist(replicate(
  n=Q, mixtureCoefSingle(
    M = P,proportions = 1,variance = 0.1
    ))[1,1,])
Y <- linearModel(X = X,B = B,E = E)
Px=M
save(list=c('X','Y','U','E','B','Z'),file=c('BayesRInput.RData'))
#scale covariates and responses to unit one variance
Y=scale(Y) 
Y=Y[,1]
X=scale(X)

RHS <- diag( (t(X) %*% X) ) 
LHS <- (t(X)%*%Y)
b_OLS <- LHS / RHS
# estimate effects by multiple regression
b_MR_OLS <- solve(t(X) %*% (X)) %*% (t(X) %*% Y)
 
```

##Unpooled model

We run stan for 4 chains. Slightly increase delta adaptation and tree depth to improve estimates in this analysis (at the expense of running time).

```{r unpooled, cache=T}
options(mc.cores = parallel::detectCores())

modelUnpooled<- stan_model(file = "BayesRUnPooled.stan",auto_write = T)




BayesFitUnpooled<-sampling(modelUnpooled,chains=4,warmup=1000,iter=2000,control = list(max_treedepth = 10,adapt_delta=0.85))
#T Use this for very quick but maybe unstable inferences
#BayesFitUnpooled<-vb(modelUnpooled)
 stan_effects<- rstan::get_posterior_mean(BayesFitUnpooled,'beta')
 rstan::stan_diag(BayesFitUnpooled)
 

Bl<-log10(abs(B))
 b_MR_OLSl<-log10(abs(b_MR_OLS))
 stan_effects<-log10(abs(stan_effects))
 plot(Bl[,1],Bl[,1],type="l",main="individual chain means for BayesR Pooled ",xlab="True effects(log10-absolute)",ylab="Estimated effects(log10-absolute)") 
 points(x=Bl[,1],y=b_MR_OLSl,pch = 23,col="black")
 points(x=Bl[,1],y=stan_effects[,1],col="yellow")
 points(x=Bl[,1],y=stan_effects[,2],col="red")
 points(x=Bl[,1],y=stan_effects[,3],col="blue")
 points(x=Bl[,1],y=stan_effects[,4],col="green")
 legend("bottomright",pch = c(23),legend = "OLS")
 stan_effects<-colMeans(extract(BayesFitUnpooled,"beta")$beta)
 stan_effects<-log10(abs(stan_effects))
 
 plot(Bl[,1],Bl[,1],type="l",main=" mean BayesR Pooled ",xlab="True effects(log10-absolute)",ylab="Estimated effects(log10-absolute)") 
 points(x=Bl[,1],y=b_MR_OLSl,pch = 23,col="black")
 points(x=Bl[,1],y=stan_effects,col="red")
 legend("bottomright",pch = c(23),legend = "OLS")
 
 traceplot(BayesFitUnpooled,pars="tau")
 traceplot(BayesFitUnpooled,pars="sigma")
 pairs(BayesFitUnpooled,pars=c("tau","sigma"))
 
 
```

##Pooled model

```{r,cache=T}
modelPooled<- stan_model(file = "BayesRPooled.stan",auto_write = T)
BayesFitPooled<-sampling(modelPooled,chains=4,warmup=2000,iter=4000,control = list(max_treedepth = 10,adapt_delta=0.85))
#Use this for very quick but maybe unstable inferences
#BayesFitPooled<-vb(modelPooled)

 rstan::stan_diag(BayesFitPooled)
 
 stan_effects<- rstan::get_posterior_mean(BayesFitPooled,'beta')
 
 
 ssPooled<- shinystan::as.shinystan(BayesFitPooled)
 Bl<-log10(abs(B))
 b_MR_OLSl<-log10(abs(b_MR_OLS))
 stan_effects<-log10(abs(stan_effects))
 plot(Bl[,1],Bl[,1],type="l",main="individual chain means for BayesR Pooled ",xlab="True effects(log10-absolute)",ylab="Estimated effects(log10-absolute)") 
# axis(side=1, at=c(-6,-4,-3,-2,-1), c("1e-5","1e-4","1e-3","1e-2","1e-1"))
# axis(side=2,at=c(-6,-4,-3,-2,-1), c("1e-5","1e-4","1e-3","1e-2","1e-1"))
 points(x=Bl[,1],y=b_MR_OLSl,pch = 23,col="black")
 points(x=Bl[,1],y=stan_effects[,1],col="yellow")
 points(x=Bl[,1],y=stan_effects[,2],col="red")
 points(x=Bl[,1],y=stan_effects[,3],col="blue")
 points(x=Bl[,1],y=stan_effects[,4],col="green")
 legend("bottomright",pch = c(23),legend = "OLS")
 stan_effects<-colMeans(extract(BayesFitPooled,"beta")$beta)
 stan_effects<-log10(abs(stan_effects))
 
 plot(Bl[,1],Bl[,1],type="l",main=" mean BayesR Pooled ",xlab="True effects(log10-absolute)",ylab="Estimated effects(log10-absolute)") 
# axis(side=1, at=c(-6,-4,-3,-2,-1), c("1e-5","1e-4","1e-3","1e-2","1e-1"))
# axis(side=2,at=c(-6,-4,-3,-2,-1), c("1e-5","1e-4","1e-3","1e-2","1e-1"))
 points(x=Bl[,1],y=b_MR_OLSl,pch = 23,col="black")
 points(x=Bl[,1],y=stan_effects,col="red")
 legend("bottomright",pch = c(23),legend = "OLS")
 
 traceplot(BayesFitPooled,pars="tau")
 traceplot(BayesFitPooled,pars="sigma")
 pairs(BayesFitPooled,pars=c("tau","sigma"))
```

##Fit Summaries

```{r}
print(summary(BayesFitUnpooled)$summary)
```

```{r}
print(summary(BayesFitPooled)$summary)
```



